### ISSUE TITLE
Create Single header only version of the library

### ISSUE THREAD

**Issue by mtangoo** [hosannahighertech/wxSimpleJSON#1]

**Comment by Blake-Madden** [comment]
In my opinion, the library is OK as it is.  wx's XML parser uses expat as a submodule and isn't a header-only system.  Nothing wrong with this library doing likewise, using cJSON as a submodule and containing a header and source file.

**Comment by mtangoo** [comment]
@Blake-Madden thanks for the comment.
That is correct. I think I need to close issues that aren't valid anymore
