### ISSUE TITLE
Log parsing errors when loading JSON content

### ISSUE THREAD

**Issue by Blake-Madden** [hosannahighertech/wxSimpleJSON#5]
When loading invalid JSON content, need to log where the parsing failure happened.

I can work on a PR for this.

**Comment by Blake-Madden** [comment]
FYI, I just updated PR #4 to include a fix for this.

**Comment by Blake-Madden** [comment]
New `GetLastError()` function adds this functionality.

**Comment by mtangoo** [comment]
Hi @Blake-Madden 
Can you open a different pull request instead of updating existing?
Thanks for your work!

**Comment by Blake-Madden** [comment]
Sorry about that, I'm a bit new to git PRs.  I see how to make separate branches for different PRs now, and I'll be sure to do that in the future.

**Comment by mtangoo** [comment]
No problem at all!
